# Generated by Django 5.0.6 on 2024-06-30 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_prices', models.FloatField()),
                ('discount_prices', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('categorty', models.CharField(choices=[('L', 'Lehenga'), ('s', 'Saree'), ('Gp', 'Gents Pant'), ('Bk', 'Borkha'), ('Bf', 'Baby fasion')], max_length=2)),
                ('product_image', models.ImageField(upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Tangail', 'Tangail'), ('Gazipur', 'Gazipur'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('shaerpur', 'shaerpur')], max_length=50)),
                ('distract', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('villageroad', models.CharField(max_length=100)),
                ('zipcoe', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
