# Generated by Django 5.0.6 on 2024-06-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorty',
            field=models.CharField(choices=[('L', 'Lehenga'), ('s', 'Saree'), ('Gp', 'Gents Pant'), ('Sh', 'TShart'), ('Lp', 'Laptop')], max_length=2),
        ),
    ]
